### ISSUE TITLE
ртп по аду

### ISSUE THREAD

**Issue by lol1d1** [Overwrite987/OvRandomTeleport#10]
ртп по аду работает странно, постоянно спавнит либо в блоках, либо вообще в одиночном источнике лавы (хотя лава в блеклисте). при этом ртп по обычному миру и энду работает отлично

**Comment by Overwrite987** [comment]
> ртп по аду работает странно, постоянно спавнит либо в блоках, либо вообще в одиночном источнике лавы (хотя лава в блеклисте). при этом ртп по обычному миру и энду работает отлично

Этого не должно происходить, однако проверю

**Comment by lol1d1** [comment]
https://github.com/user-attachments/assets/adf0a2fa-8651-482b-9b0f-a90364a611fa

**Comment by Overwrite987** [comment]
Скачать обновлённую версию можно в Actions
