### ISSUE TITLE
новый плейсхолдер

### ISSUE THREAD

**Issue by lol1d1** [Overwrite987/OvRandomTeleport#11]
предлагаю добавить плейсхолдер, который будет отображать, какое кд установлено для группы игрока. это очень удобно для оформления менюшек, чтобы наглядно было видно какая задержка будет у игрока при ртп если у него какой то конкретный донат. соответственно, если у игрока нет нужной привелегии, будет выводиться время по умолчанию. это значение будет постоянным, не должен идти никакой отчет во время перезарядки.

в общем, просто фишка для более понятного оформления менюшек, буду очень признателен, если добавите.

**Comment by Overwrite987** [comment]
> предлагаю добавить плейсхолдер, который будет отображать, какое кд установлено для группы игрока. это очень удобно для оформления менюшек, чтобы наглядно было видно какая задержка будет у игрока при ртп если у него какой то конкретный донат. соответственно, если у игрока нет нужной привелегии, будет выводиться время по умолчанию. это значение будет постоянным, не должен идти никакой отчет во время перезарядки.
> 
> в общем, просто фишка для более понятного оформления менюшек, буду очень признателен, если добавите.

Вероятно - добавлю, выглядит логично, но раз на то пошло - вероятно, можно будет доставить и остальные настройки в качестве плейсхолдеров

**Comment by Overwrite987** [comment]
Итак, в дев билде добавлен ряд новых плейсхолдеров.
По твоей теме:
%ovrtp_settings_default_cooldown_default% - выводит дефолтный КД
%ovrtp_settings_default_cooldown_by_group% - выводит КД в зависимсти от группы игрока

**Comment by lol1d1** [comment]
плейсхолдер %ovrtp_settings_default_cooldown_by_group% не работает, хотя остальные все настройки вроде норм выводятся.

так же попробовал %ovrtp_settings_default_cooldown_by_player_group% (судя по коду именно так правильно), он тоже не работает

> Итак, в дев билде добавлен ряд новых плейсхолдеров. По твоей теме: %ovrtp_settings_default_cooldown_default% - выводит дефолтный КД %ovrtp_settings_default_cooldown_by_group% - выводит КД в зависимсти от группы игрока
