### ISSUE TITLE
новый плейсхолдер не работает

### ISSUE THREAD

**Issue by lol1d1** [Overwrite987/OvRandomTeleport#13]
плейсхолдер %ovrtp_settings_default_cooldown_by_group% не работает, хотя остальные все настройки вроде норм выводятся.

так же попробовал %ovrtp_settings_default_cooldown_by_player_group% (судя по коду именно так правильно), он тоже не работает

**Comment by Overwrite987** [comment]
> плейсхолдер %ovrtp_settings_default_cooldown_by_group% не работает, хотя остальные все настройки вроде норм выводятся.
> 
> так же попробовал %ovrtp_settings_default_cooldown_by_player_group% (судя по коду именно так правильно), он тоже не работает

Да, там надо кое что переделать
