### ISSUE TITLE
[Предложение] Добавить пермишен/настройку по группам для cooldown.teleport_cooldown

### ISSUE THREAD

**Issue by Iarkont** [Overwrite987/OvRandomTeleport#7]
Плагину действительно не хватает какой либо настройки для КД до телепортации.
к примеру:
cooldown:
  default_teleport_cooldown: 5
  group_teleport_cooldowns:
      default: 5
      vip: -1
Либо же пермишена который будет байпасить КД до телепортации

**Comment by Iarkont** [comment]
+ Баг заметил — игнорирует блок POWDER_SNOW (во многих плагинах на ртп почему-то он игнорируется) 
Тоесть, если запретить в кфг тп на этот блок, то плагин проигнорирует и всё равно телепортирует в рыхлый снег. хех

**Comment by Overwrite987** [comment]
> * Баг заметил — игнорирует блок POWDER_SNOW (во многих плагинах на ртп почему-то он игнорируется)
>   Тоесть, если запретить в кфг тп на этот блок, то плагин проигнорирует и всё равно телепортирует в рыхлый снег. хех

Такого блока не существует...
Ты неверно указал ID.

**Comment by Overwrite987** [comment]
> Плагину действительно не хватает какой либо настройки для КД до телепортации. к примеру: cooldown: default_teleport_cooldown: 5 group_teleport_cooldowns: default: 5 vip: -1 Либо же пермишена который будет байпасить КД до телепортации

Иногда нужно просто лучше читать описание плагина. 
Это написано в описании прав - rtp.near.bypass

**Comment by Iarkont** [comment]
Всмысле такого блока не существует. Всё правильно указывал. 
![IMG_20241107_172322_431](https://github.com/user-attachments/assets/0540cfb1-95ec-4fd7-b2e1-016197810e52)
![IMG_20241107_172326_118](https://github.com/user-attachments/assets/455739d2-885b-4419-8a76-60e88957c7ca)


А во вторых пермишена который байпасит обратный отчёт до ртп не существует (версия плуга последняя с гита)

**Comment by Overwrite987** [comment]
> Всмысле такого блока не существует. Всё правильно указывал. ![IMG_20241107_172322_431](https://private-user-images.githubusercontent.com/75908293/384011304-0540cfb1-95ec-4fd7-b2e1-016197810e52.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTE2OTYsIm5iZiI6MTczMDk5MTM5NiwicGF0aCI6Ii83NTkwODI5My8zODQwMTEzMDQtMDU0MGNmYjEtOTVlYy00ZmQ3LWIyZTEtMDE2MTk3ODEwZTUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE0NTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ZGEzNzViMjQwYzgxYjBmZmE2OTczMGJkMTVhZmIyOGVkMzVkZDRhMTY5ZjE5MjNlOTdjOTk5MDE3YTc3ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mViN4CAK41JKljgFQJ77c5qcO8r3mXw0KTSLQfdsIpQ) ![IMG_20241107_172326_118](https://private-user-images.githubusercontent.com/75908293/384011319-455739d2-885b-4419-8a76-60e88957c7ca.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTE2OTYsIm5iZiI6MTczMDk5MTM5NiwicGF0aCI6Ii83NTkwODI5My8zODQwMTEzMTktNDU1NzM5ZDItODg1Yi00NDE5LThhNzYtNjBlODg5NTdjN2NhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE0NTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiN2Y3NTM5NTc2YzA5NTU5MGFhYTA3MGM0MzI4ZmYyYWYwMzM0ZTI3NGY2MDk1YzY3MTkzYTQ0OGE0OTZkNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NCDvrjXtW0dRYmT3Lkx-mxKJE9j1AtXQx2VyP4mzFng)
> 
> А во вторых пермишена который байпасит обратный отчёт до ртп не существует (версия плуга последняя с гита)

Занятно, в идее сначала не подсказывало. Но раз так - тогда встаёт вопрос о том, как это работает

**Comment by Iarkont** [comment]
кажется на 1.20.4 purpur не хочет работать, даже в tab_complete через lp не отображается пермишен rtp.near.bypass
если даже добавить изменений не произойдёт.
может этот пермишен нужен для бупаса кд до ртп к игроку? а то прописываю с этим пермишеном /rtp (обычный дефолт ртп) и всё равно начинается обратный отсчёт до ртп

**Comment by Overwrite987** [comment]
> кажется на 1.20.4 purpur не хочет работать, даже в tab_complete через lp не отображается пермишен rtp.near.bypass если даже добавить изменений не произойдёт. может этот пермишен нужен для бупаса кд до ртп к игроку? а то прописываю с этим пермишеном /rtp (обычный дефолт ртп) и всё равно начинается обратный отсчёт до ртп

А при чем тут таб комплит к ЛП, а также обратный отсчет? Это пре телепорт кулдаун, а не кулдаун. Если речь про него - то на него нет и не будет обхода

**Comment by Iarkont** [comment]
понял

**Comment by Overwrite987** [comment]
> Всмысле такого блока не существует. Всё правильно указывал. ![IMG_20241107_172322_431](https://private-user-images.githubusercontent.com/75908293/384011304-0540cfb1-95ec-4fd7-b2e1-016197810e52.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDgwMTgsIm5iZiI6MTczMTYwNzcxOCwicGF0aCI6Ii83NTkwODI5My8zODQwMTEzMDQtMDU0MGNmYjEtOTVlYy00ZmQ3LWIyZTEtMDE2MTk3ODEwZTUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDE4MDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmN2RiZWUyOTQ2MjU3MmI0NmJjMjA1OWM1NWRiNTE2OTUxM2U0MWI1M2VmZmRiYWYwNjlmNDkxNWRjMWRiNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h0zvt4BLHAvBuXBtsT868AYEHSXY_Wwp65GSgJTH3oM) ![IMG_20241107_172326_118](https://private-user-images.githubusercontent.com/75908293/384011319-455739d2-885b-4419-8a76-60e88957c7ca.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDgwMTgsIm5iZiI6MTczMTYwNzcxOCwicGF0aCI6Ii83NTkwODI5My8zODQwMTEzMTktNDU1NzM5ZDItODg1Yi00NDE5LThhNzYtNjBlODg5NTdjN2NhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDE4MDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MTlhMTE3MjRlYzlmZTFlMTI5ODE1YzdhOWQ1OTFlNzYzZTk5YzZlNjc5ZTE2YzFjYzU4MTQzZjkxZDBlNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x4M4XTCY17aOcLMhLP8oBjFPHWYIihSWaqqm0er6OHo)
> 
> А во вторых пермишена который байпасит обратный отчёт до ртп не существует (версия плуга последняя с гита)

Данная проблема была исправлена в последнем пре-релизе
