### ISSUE TITLE
Ошибка при запуске сервера 1.21.3

### ISSUE THREAD

**Issue by TheFaik** [Overwrite987/OvRandomTeleport#9]
Вот ошибка - https://pastebin.com/uLLdLV5p
Я обновил сервер с Leaf 1.21.1 на 1.21.3 и при запуске сервера, выскакивает ошибка.

**Comment by Overwrite987** [comment]
> Вот ошибка - https://pastebin.com/uLLdLV5p Я обновил сервер с Leaf 1.21.1 на 1.21.3 и при запуске сервера, выскакивает ошибка.

java.lang.ClassCastException: interface org.bukkit.block.Biome not an enum

Я даже боюсь предположить, что сделали моджанги в новой версии...

Я конечно посмотрю, но мне что-то подсказывает, что на этом как-бы история и кончается

**Comment by Overwrite987** [comment]
Чтож, это я готов сказать ПУШКА, по тому что, чтобы сделать то, что всё время работало вот ТАК: https://jd.papermc.io/paper/1.21.3/org/bukkit/block/Biome.html
У меня нет слов

Но тем не менее - это ХОТЯ БЫ фиксится

**Comment by Overwrite987** [comment]
Исправлено.
Дев билд с исправлением можно скачать тут: https://github.com/Overwrite987/OvRandomTeleport/actions
